### ISSUE TITLE
班主用的什么打包工具？

### ISSUE THREAD

**Issue by Yayhub** [Eanya-Tonic/MihiroToolbox#3]
exe打包工具是nuitka还是pyinstaller?

**Comment by Eanya-Tonic** [comment]
我用的是pyinstaller

**Comment by Eanya-Tonic** [comment]
`pyinstaller.exe --icon=.\img\logo.ico .\MihiroToolBox.py --noconsole`
大致是这样，我将关闭这个issue，如有问题欢迎您重新提出新的issue或重新打开
