### ISSUE TITLE
请求增加保留原音频选项

### ISSUE THREAD

**Issue by amokiel** [Eanya-Tonic/MihiroToolbox#4]
压缩视频时发现音频只能压缩，不能选择保留原音频，这一点体验略有不足。其它部分完美符合需求，速度很快，效果也很好！开发者辛苦了，希望可以增加一个

**Comment by Eanya-Tonic** [comment]
[v1.1.2](https://github.com/Eanya-Tonic/MihiroToolbox/releases/tag/v1.1.2)，已在1.1.2版本中更新复制音频流，我将关闭这个issue，如有问题欢迎您重新提出新的issue
